# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904fa6250ad3f92c63e37e327cb76738e647fdf0f9c3875056ff9afc51df16decf5b78a4a1c540adf0da22d395d5f13104353af3fff3dc9ac6aa033a67e33628

test:
  secret_key_base: fa543622973ea2ade3187ea783f8f63d02f7fc85014d99652d97d1929e3df07bc3adf3cce58624d5330f2c643ee652506878b5bd1f8216865bcd0dec9083be25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
